name: 'Update PR label'
on:
  pull_request:
    types: [opened, reopened, 'edited', 'closed']
  issue_comment:
    types: [created]

jobs:
  set_xrp_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check donation request
        id: check
        uses: ./
        with:
          address: ${{ secrets.XRP_OWNER_ADDRESS }}
          network: testnet
          pr-number: ${{ github.event.number }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          XRP_DONATION_URL: https://xrp-donation-app.vercel.app
      - name: Get status
        run: echo "Return status ${{ steps.check.outputs.status }}"
      - name: Get data
        run: echo "Return data ${{ steps.check.outputs.data }}"
